#!/bin/bash

unset GEM_HOME
unset GEM_PATH

CREW_FILE_DIR=$(dirname $0)
CREW_HOST_OS=`uname -s | tr '[:upper:]' '[:lower:]'`
CREW_HOST_CPU=`uname -m`
CREW_32BIT_HOST_CPU=${CREW_HOST_CPU%_64}

if [ -z $SSL_CERT_FILE ]; then
    SSL_CERT_FILE="$CREW_FILE_DIR/etc/ca-certificates.crt"
fi

if [ -z $CREW_RUBY_DIR ]; then
    if [ -d "$CREW_FILE_DIR/../../prebuilt/$CREW_HOST_OS-$CREW_HOST_CPU" ]; then
        CREW_RUBY_DIR="$CREW_FILE_DIR/../../prebuilt/$CREW_HOST_OS-$CREW_HOST_CPU/bin"
    else
        CREW_RUBY_DIR="$CREW_FILE_DIR/../../prebuilt/$CREW_HOST_OS-$CREW_32BIT_HOST_CPU/bin"
    fi
fi

export SSL_CERT_FILE

exec $CREW_RUBY_DIR/ruby -W0 "$CREW_FILE_DIR/crew.rb" "$@"
